DROP TABLE IF EXISTS quiz_attempts CASCADE;

CREATE TABLE quiz_attempts (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
  answer_one VARCHAR(255) NOT NULL,
  answer_two VARCHAR(255) NOT NULL,
  answer_three VARCHAR(255) NOT NULL,
  answer_four VARCHAR(255) NOT NULL,
  quiz_result INTEGER NOT NULL
);
